# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 569dff55ac83f64e1031c6ea76fad6c3ccb2eae221c2d124dfb7009bf70433ffc69c7615b12f5e283e791352288067f3210d8c1cd4a8d1ae0a2b86c0d1c88c1c

test:
  secret_key_base: 090837322b9de019d0d65e749861ef1d6e48c82ed0096297caa81e49f7c33b4d91755d53e7ae8c247f9da04cf797dca962c8cb0d6b64811d1f470b59e44a6061

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
